# Generated by Django 3.2.5 on 2021-07-05 18:46

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='О себе')),
                ('photo', models.ImageField(upload_to='authors/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('publicated_date', models.DateField(auto_now=True)),
                ('banner', models.ImageField(upload_to='project_banners/', verbose_name='Баннер проекта')),
                ('main_picture', models.ImageField(upload_to='projects/', verbose_name='Главная картинка')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('url', models.SlugField(max_length=200, unique=True)),
                ('publicate', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('author', models.ManyToManyField(related_name='project_author', to='studio.Author', verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='project_shots/', verbose_name='Изображения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Картинка проекта',
                'verbose_name_plural': 'Картинки проекта',
            },
        ),
    ]
