# Generated by Django 3.2.5 on 2021-07-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview',
            field=models.ImageField(default='projects_preview/1.png', upload_to='projects_preview/', verbose_name='Превью'),
        ),
    ]
