# Generated by Django 3.2.5 on 2021-07-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_project_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to='authors/', verbose_name='Общая картинка'),
        ),
    ]
