# Generated by Django 3.2.5 on 2021-07-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password1',
            field=models.CharField(default=123, max_length=150, verbose_name='Пароль1'),
        ),
        migrations.AddField(
            model_name='author',
            name='password2',
            field=models.CharField(default=123, max_length=150, verbose_name='Пароль2'),
        ),
    ]
