# Generated by Django 3.2.5 on 2021-07-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_auto_20210714_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='author',
            name='password2',
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to='authors/', verbose_name='Фото обложки'),
        ),
    ]
