# Generated by Django 3.2.5 on 2021-07-15 08:09

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_auto_20210715_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата добавления')),
                ('number', models.CharField(max_length=50, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
    ]
